### ISSUE TITLE
Unable to install ftfy

### ISSUE THREAD

**Issue by unfolx** [LuminosoInsight/python-ftfy#100]
I cannot install ftfy on my machine (Windows 10, Python 3.6.5). This is what I have:

    python -m pip install ftfy
    
    Collecting ftfy
      Downloading https://files.pythonhosted.org/packages/07/43/759413ed05a49160d76ccb4ab26b82f7d0f0a9c8bc1e3af683c1ebab5adb/ftfy-5.4.0.tar.gz (57kB)
        100% |████████████████████████████████| 61kB 542kB/s
        Complete output from command python setup.py egg_info:
        Traceback (most recent call last):
          File "<string>", line 1, in <module>
          File "C:\Users\<username>\AppData\Local\Temp\pip-install-f8v_y6pt\ftfy\setup.py", line 19, in <module>
            DESCRIPTION = open('README.md').read()
          File "C:\Users\<username>\AppData\Local\Continuum\anaconda3\lib\encodings\cp1252.py", line 23, in decode
            return codecs.charmap_decode(input,self.errors,decoding_table)[0]
        UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 406: character maps to <undefined>
    
        ----------------------------------------
    Command "python setup.py egg_info" failed with error code 1 in C:\Users\<username>\AppData\Local\Temp\pip-install-f8v_y6pt\ftfy\

Any idea how I could solve this?

**Comment by rspeer** [comment]
Oh wow, it's a funny bug that ftfy is unable to install because it's reading one of its _own_ files in the wrong encoding.

I copied a recipe for including a README as a long description, and that recipe didn't really think about the fact that the README might be Unicode text and there are differences in Unicode defaults between different operating systems. I should just apply the usual fix of explicitly loading the file in UTF-8.

Although, I'm surprised. I thought Python on Windows defaulted to UTF-8 since 3.6. https://www.python.org/dev/peps/pep-0528/
