### ISSUE TITLE
Recognize MacRoman mojibake of common letters such as "ö"

### ISSUE THREAD

**Issue by MicroJackson** [LuminosoInsight/python-ftfy#103]
I have problems with mojibake of the letter ö in König. 
`U+00F6  ö       [Ll] LATIN SMALL LETTER O WITH DIAERESIS`

These are some examples that might be mojibaked, not sure about the first 2, just added them in case they are solvable. The first 2 look the same in the browser but different in unicode.
K�nig or K���nig
`U+FFFD  �       [So] REPLACEMENT CHARACTER`

Knig (This is mojibake-solved by ftfy.fix_text() as a `U+0022  "       [Po] QUOTATION MARK`)
`U+0094  \x94    [Cc] <unknown>`

KÃ¶nig
`U+00C3  Ã       [Lu] LATIN CAPITAL LETTER A WITH TILDE`
`U+00B6  ¶       [Po] PILCROW SIGN`

K√∂nig
`U+221A  √       [Sm] SQUARE ROOT`
`U+2202  ∂       [Sm] PARTIAL DIFFERENTIAL`

Are any of these solvable?

**Comment by rspeer** [comment]
1. ftfy doesn't restore information that's completely lost, such as anything where characters have been replaced by �, so the first example is not fixable.

2. `K\x94nig` decodes as `K”nig` when Windows-1252 and Latin-1 are mixed up. It decodes as `König` when cp437 and Latin-1 are mixed up, which is much less common. Even if we could handle cp437/Latin-1 mixups (#18), a single character wouldn't be enough information to tell them apart.

3. Good news: `KÃ¶nig` is solved by the current version of ftfy.

4. This one is _close_ to something ftfy solves; the only problem is it's too short to be confident. If it appeared as part of a longer text with more mojibake it would be fine. For example:

```
>>> ftfy.fix_text("K√∂nigK√∂nigK√∂nig")
'KönigKönigKönig'
```

In `ftfy/fixes.py`, you could change line 124 to assign 'macroman' encoding a cost of 0 instead of 2, and it would be able to fix this example, at the expense of breaking other things. (Run `pytest` to see what breaks.)

Aside from the ever-present #18, I think the possible thing that you're requesting here is to handle short, common mojibake sequences from macroman as well as we handle the ones from Windows-1252.

**Comment by rspeer** [comment]
I'm going to focus on this example, which is a minimal example of MacRoman mojibake that's entirely feasible to recognize and fix:

> K√∂nig
> `U+221A  √       [Sm] SQUARE ROOT`
> `U+2202  ∂       [Sm] PARTIAL DIFFERENTIAL`

**Comment by jbernardes** [comment]
I might have the same problem with ftfy 0.1.7

>>> test = "HÃ´tel de Police"
>>> ftfy.fix_text(test)
'HÃ´tel de Police'
>>> test.encode("latin-1").decode("utf-8")
'Hôtel de Police'

**Comment by rspeer** [comment]
I think you're looking at the version number of something else (ftfy is on version 5.6), but yes, that is an example where we fail and could have succeeded. Thanks for pointing it out.

The grave accent was missing from a heuristic that should have detected that one. #134 has the fix.

**Comment by jbernardes** [comment]
Yes we use `ftfy==5.6`, thanks for the quick fix .

**Comment by rspeer** [comment]
ftfy 5.9 (and I think also 5.8) will decode "K√∂nig" as "König".
