### ISSUE TITLE
MacRoman-CP437

### ISSUE THREAD

**Issue by hajdbo** [LuminosoInsight/python-ftfy#105]
I came across a file that went through an old Mac and an old PC, and is now on a Linux ext4 filesystem.

Filename string bytes as given by debugfs: journ\xc3\x87e.txt displayed as "journÇe.txt" in UTF-8. The correct filename should have been "journée.txt".

```
In [11]: bytes('journÇe','utf-8')
Out[11]: b'journ\xc3\x87e'

In [12]: bytes('journÇe','macroman')
Out[12]: b'journ\x82e'

In [13]: bytes('journée','cp437')
Out[13]: b'journ\x82e'

In [14]: bytes('journée','utf8')
Out[14]: b'journ\xc3\xa9e'
```

The filename is in french.
French 15th most frequent letter (> 2%) is diacritic e: é.
French bigrams containing the letter é are frequent too, with 4 in the top 100.
So there is a point to solve this problem.

Currently FTFY is not detecting/correcting the string:
```
In [68]: print(ftfy.fix_encoding(u'journ\xc3\x87e'))
journÇe

In [69]: print(ftfy.fix_text(u'journ\xc3\x87e'))
journÇe
```

We can use iconv to fix the filename:
```
➜  ls journÇe.txt
journÇe.txt
➜  ls journÇe.txt | iconv -f utf8 -t mac | iconv -f cp437 -t utf8
journée.txt
```

**Comment by hajdbo** [comment]
examples in the wild: [google search for libertÇ](https://www.google.com/search?q=%27libert%C3%87%27&nirf=%27libert%27)

**Comment by rspeer** [comment]
I'm going to consider this issue part of #18. That's not to say it's not important -- it's just hard. I think that #18 is the biggest functionality gap in ftfy, and I welcome any suggestions at all for how to address it.

**Comment by Macro-Jackson** [comment]
Hi Rob, first of all my compliments for this awesome framework.

I'd like to share my thoughts on this matter. I ain't a programmer or a ML specialist but I do have a bit of technical knowledge of online software, data frameworks and applications. Nor do I exactly know how FTFY works on code level, I just think I understand the general concept.

The first question is do you want to setup more context to decide the possible solution? Looking at a single problem or a single string might give you an idea on a solution but then you presume all mojibake problems are equal, which as we can see is not always true. 

So in the cases where the solutions might not be that easy you need to know more before you can be sure so fix the issue otherwise you might change something wrong. 

sidestep: Now that is already a good question. Is the fix worst then the error if it is done. Lets say of all the issues FTFY can't fix that it would make the best guess, that 80% is guessed right. Then I as a user should have that option to take that risk. So a setting how secure/sure FTFY must be before fixing the mojibake. /sidestep

Now to get more context you can add a ton of options. Some hard, some more easy, most cost processing time etc etc. But I always like the easy solutions, something that is already there and might not be the magical solution but at least makes a significant dent in the problems.
So what about that the user can give context. For example in our case we know what language the string is and therefor/also we know the allowed characters. That information should give FTFY more information about the possible solution. 

Second idea that I had is: with a bit more effort is to send more strings to see if in lets say 100 unfixable strings with 2 or 3 or 4 fixes can be solved. As this gives you a ton of more context on the problems in general, it must give you far more statistics on the probability if the fix will be correct.

 Third idea is: Work together. And I mean FTFY with a human. And make a start in ML. So let FTFY suggest solutions and let the user decide. Based on these decisions suggest solutions in other equal mojibake problems and if more then x times this fix has been decided that it automatically applies this next time. Again with this you set context and "learn" FTFY a fix for your case.

I hope this shines some light on your question or at least gives you some new ideas.

Just my 2 cents.
