### ISSUE TITLE
Installation fails

### ISSUE THREAD

**Issue by aserebrenik** [LuminosoInsight/python-ftfy#112]
Alexanders-MacBook-Pro:python-ftfy-master aserebrenik$ python setup.py install
Traceback (most recent call last):
  File "setup.py", line 19, in <module>
    DESCRIPTION = open('README.md', encoding='utf-8').read()
TypeError: 'encoding' is an invalid keyword argument for this function

**Comment by okin** [comment]
What Python version are you using?
You can find out by running `python --version`.

The current version does not support Python 2 anymore (see [README](https://github.com/LuminosoInsight/python-ftfy#installing) and you will have to use an older version (i.e. _v4.4.1_).

**Comment by aserebrenik** [comment]
3.4.1

**Comment by rspeer** [comment]
Please run `python --version` in the same environment that you're running `python setup.py install`. The error message is a strong indication that you're accidentally running it with Python 2.

On the other hand, this means that the code path that was supposed to warn about Python 2 isn't working, because the `DESCRIPTION` definition was moved.

**Comment by rspeer** [comment]
#113 should resolve this by making the Python 2 message more helpful.
