### ISSUE TITLE
ftfy.fix_text() not fixing encoding errors on strings with UPPER case

### ISSUE THREAD

**Issue by CyanBC** [LuminosoInsight/python-ftfy#123]
Python 3.6.8 64bit windows. Fyfy 5.5.1

```
ftfy.fix_text('Colombia, Boyaca, PUERTO BOYACÁ, BoyacÃ¡. Puerto BoyacÃ¡. Vda La Fiebre')
'Colombia, Boyaca, PUERTO BOYACÁ, BoyacÃ¡. Puerto BoyacÃ¡. Vda La Fiebre'
```

will not return any changes

```
ftfy.fix_text('Colombia, Boyaca, BoyacÃ¡. Puerto BoyacÃ¡. Vda La Fiebre')
'Colombia, Boyaca, Boyacá. Puerto Boyacá. Vda La Fiebre'
```

will have changes.

I can workaround using:
```
input_text = 'Colombia, Boyaca, PUERTO BOYACÁ, BoyacÃ¡. Puerto BoyacÃ¡. Vda La Fiebre'
" ".join([ftfy.fix_text(i) for i in input_text.split()])

'Colombia, Boyaca, PUERTO BOYACÁ, Boyacá. Puerto Boyacá. Vda La Fiebre'
```

But this is less than ideal.

Is there a reason fix_text gives up after upper case segment?

**Comment by rspeer** [comment]
It's not because it's in uppercase, it's because the text "PUERTO BOYACÁ" is correctly encoded. The same fix that fixes "BoyacÃ¡" would turn "BOYACÁ" into "BOYAC�". If you had "Puerto Boyacá" there it would cause the same result.

ftfy doesn't currently try to detect changes of encoding within a line.

Trying each word in a separate encoding like you're doing is fine if that's what you need. You could also use `fix_text_segment(i)` instead of `fix_text(i)` on each word, to make it a little simpler and faster when you're already telling it that each word is a separate segment.

**Comment by CyanBC** [comment]
Thank you for your response. That makes sense. I shouldn't have doubted you.
