### ISSUE TITLE
ftfy.fix_text("árvíztűrő tükörfúrógép".encode('utf-16').decode('windows-1252')) returns mojibake

### ISSUE THREAD

**Issue by Googulator** [LuminosoInsight/python-ftfy#124]
UTF-16 repair of accented characters appears to have issues.
The sequence:

`ftfy.fix_text("árvíztűrő tükörfúrógép".encode('utf-16').decode('windows-1252'))`

returns "ÿþárvíztqrQ tükörfúrógép"

There are 2 issues here:
- The BOM fails to be removed
- the letters "ő" and "ű" (which have code points above U+255) are decoded incorrectly; only the low 8 bytes of the UTF-16 value are used.

**Comment by rspeer** [comment]
UTF-16 mojibake is out of scope and I don't even see it much in the wild. If you have UTF-16 mojibake, you _know_, and you clearly need to fix it at the source because there is not a single string that would make it through correctly.

I don't have any intent for ftfy to ever modify ASCII letters such as "Q", including by guessing that they came from UTF-16.

**Comment by rspeer** [comment]
For an example of why it would be unwise to fix UTF-16 mojibake, there's a classic Windows bug that detected UTF-16 in the text ["this api can break" or "this app will break"](http://www.timlesher.com/2006/06/this-api-can-break.html).
