### ISSUE TITLE
ftfy.fix_text(fix_entities=True) doesn't fix capitalized, escaped, accented characters and Ñ

### ISSUE THREAD

**Issue by amyspark** [LuminosoInsight/python-ftfy#125]
I've got these bits of text from a CSV. The source seems to have mistakenly encoded `É`, `Á` and `Ñ` into their HTML equivalents.

```
273953;"SOFIA P&EACUTE;REZ LUJ&AACUTE;N";11;1;939;1
323720;"ORDO&NTILDE;EZ, MERCEDES";6;1;711;1
```

When repairing each cell using `ftfy.fix_text(row[col], fix_entities=True)`, shouldn't these be fixed as well? (I did try manually replacing them with their lowercase equivalents and ftfy correctly fixes them.)

**Comment by rspeer** [comment]
Hm, it's interesting, because we can look at that text and understand what it meant to say. But there _is_ some data loss here, because HTML entities are case-sensitive. I notice that ftfy agrees with the builtin `html.unescape` here:

```python
>>> import html

>>> html.unescape('&eacute;')
'é'

>>> html.unescape('&Eacute;')
'É'

>>> html.unescape('&EACUTE;')
'&EACUTE;'
```

But then, in this case, the data loss that has occurred apparently doesn't _matter_. The reason we got HTML entities in all caps is because the text is in all caps. We could just assume the letters we're supposed to decode are the uppercase ones.

This has also made me realize that all currently supported versions of Python 3 have `html.unescape` in the standard library. If we _don't_ need to support entities that have been converted to all caps, ftfy could just drop its custom HTML unescaping code and use the standard library now.

**Comment by rspeer** [comment]
So I guess I have a follow-up question. Although it's not standard to decode HTML entities that are in all caps, if everything that happened to text was standard there would be no need for ftfy in the first place.

So how widespread do you think this kind of text is? Would fixing it be a sufficiently-desired new feature?

**Comment by amyspark** [comment]
@rspeer, The snippet above was taken from the "[Producciones científico-tecnológicas](https://datos.gob.ar/dataset/mincyt-producciones-cientifico-tecnologicas)" (scientific and technological productions) dataset of the Secretariat of Science and Technology of Argentina.
I've had to massively `sed` their tables because of the amount of encoding errors they have, so I bet all their datasets could potentially have the same issue.

**Comment by rspeer** [comment]
The situation with case sensitivity and ambiguity is worse than I'd hoped. HTML entities apparently use case sensitivity not just for lowercase vs. uppercase letters, but for doubling things in symbols?

And yet I still understand specifically what &NTILDE; is and it couldn't be anything else.

```
>>> import html

>>> html.unescape('&dot;')
'˙'

>>> html.unescape('&Dot;')
'¨'

>>> html.unescape('&otimes;')
'⊗'

>>> html.unescape('&Otimes;')
'⨷'

>>> html.unescape('&and;')
'∧'

>>> html.unescape('&And;')
'⩓'

>>> html.unescape('&pr;')
'≺'

>>> html.unescape('&Pr;')
'⪻'

>>> html.unescape('&sup;')
'⊃'

>>> html.unescape('&Sup;')
'⋑'

>>> html.unescape('&not;')
'¬'

>>> html.unescape('&Not;')
'⫬'

>>> html.unescape('&sube;')
'⊆'

>>> html.unescape('&subE;')
'⫅'
```

**Comment by rspeer** [comment]
Okay, I came up with a coherent enough fix that covers common Latin letters (with codepoints below U+300), and also updates the rest of how we handle entities: #126

**Comment by rspeer** [comment]
It took another revision of the fix to avoid causing all kinds of false positives, but it's in now. ftfy 5.6 can decode `P&EACUTE;REZ` and `ORDO&NTILDE;EZ` and so on. Thanks for the suggestion!
