### ISSUE TITLE
fix_entities strips entity-encoded U+FFFE

### ISSUE THREAD

**Issue by kblomster** [LuminosoInsight/python-ftfy#129]
`ftfy.fix_text('&#65534;', fix_entities=True)` returns an empty string. I would have expected U+FFFE, which is otherwise left intact.

I'm not actually sure what the correct unescaping behaviour is here according to the standards, but `'\ufffe'.encode('ascii', 'xmlcharrefreplace').decode('ascii')` generates it (which is how I ran into the issue - we use that method to generate strings with entities in our unit tests, and Hypothesis happened to generate U+FFFE).

edit: I wrote U+FFFD by mistake when I meant to write U+FFFE. Fixed now.

**Comment by rspeer** [comment]
This is the correct output defined by the Python standard library. For example, you can see the same result without using ftfy:

```
>>> import html
>>> html.unescape('&#65534;')
''
```

U+FFFE should never appear in a string meant for interchange, and in fact its purpose is to be a guaranteed-invalid codepoint that signals that you're decoding UTF-16 with the bytes swapped.

Python's html library aims to produce reasonable Unicode output even in the presence of unreasonable input. It doesn't want to take in the ASCII string `&#65534;` and produce the UTF-16-breaking string `\ufffe`, so it produces the empty string instead.

**Comment by kblomster** [comment]
@rspeer I see, thanks for the explanation! I have a follow-up question though, if you don't mind: would it be reasonable for `fix_text` to strip U+FFFE as well? With the current behavior it's stripped if it appears as an XML entity but left intact if it appears verbatim, which is at least mildly inconsistent. It's no big deal for me either way, just wondering if there's a reason for keeping it that goes over my head.

**Comment by rspeer** [comment]
You're right -- it would make sense for ftfy to strip noncharacters because of the goal of taking in bad text and outputting good text.

I can see that the codepoint U+FFFE has a purpose as an "oh no I decoded this wrong" signal, but if you are in the position to do something about decoding things wrong, you're in the position to fix it without having to pass the string through ftfy. And it's as much of a signal as, say, U+0090, which is removed by `remove_control_chars`.

Should we strip noncharacters as part of the `remove_control_chars` rule? Adding a new rule would require a new major version and make the function signature even more unwieldy.

**Comment by kblomster** [comment]
> Should we strip noncharacters as part of the `remove_control_chars` rule? Adding a new rule would require a new major version and make the function signature even more unwieldy.

As a user of the library with at least some basic familiarity with Unicode I think that sounds like a good idea in line with what I'd expect `fix_text` to do, and personally I can't really see a scenario where you'd want to use `fix_text` but also keep non-characters around. I'm definitely not an expert on Unicode though and I don't know if a change like that could impact other fixers or the "badness detection", so that's a caveat.
