### ISSUE TITLE
Unit test fails with Python 3.8.1

### ISSUE THREAD

**Issue by danieldk** [LuminosoInsight/python-ftfy#131]
Running the unit tests with Python 3.8.1 fails with the following error:

```
=================================== FAILURES ===================================
_____________________________ test_bmp_characters ______________________________

    def test_bmp_characters():
        for index in range(0xa0, 0xfffd):
            char = chr(index)
            # Exclude code points that are not assigned
            if unicodedata.category(char) not in ('Co', 'Cn', 'Cs', 'Mc', 'Mn', 'Sk'):
                garble = char.encode('utf-8').decode('latin-1')
                # Exclude characters whose re-encoding is protected by the
                # 'sequence_weirdness' metric
                if sequence_weirdness(garble) >= 0:
                    garble2 = char.encode('utf-8').decode('latin-1').encode('utf-8').decode('latin-1')
                    for garb in (garble, garble2):
                        fixed, plan = fix_encoding_and_explain(garb)
>                       assert fixed == char
E                       AssertionError: assert 'à±·' == '౷'
E                         - à±·
E                         + ౷

tests/test_characters.py:23: AssertionError
=================== 1 failed, 186 passed, 8 xfailed in 1.84s ===================
```

Python 3.7.6 does not produce this error.

**Comment by danieldk** [comment]
Adding a screenshot with the rendered characters:

![Screenshot from 2020-01-28 08-03-51](https://user-images.githubusercontent.com/49398/73242269-d0b22800-41a4-11ea-86d3-45ddca41b7e3.png)

**Comment by Tahnan** [comment]
@danieldk - looks like U+0C77 TELUGU SIGN SIDDHAM was added to Unicode in 2019 as part of Unicode 12.0.  Definitely a good addition on their part, but it means that the character has gone from category `Cn` ("other, not assigned") to category `Po` ("punctuation, other").  Since this test only checks a character `if unicodedata.category(char) not in ('Co', 'Cn', 'Cs', 'Mc', 'Mn', 'Sk')`, U+0C77 is skipped in Python 3.6, whose `unicodedata` is compiled (per Python documentation) from Unicode 9.0, but not in Python 3.8, whose `unicodedata` is compiled from 12.1.0.

Robyn's currently at a conference, so she's probably not going to see this until she gets back, but when she does I'll see what she thinks about fixing it.  (I'd look into it myself, but I'm stalled at step one, "Get a Python 3.8 environment". :-) )

**Comment by rspeer** [comment]
Yep, thanks. This is a routine update we have to make to ftfy (to save the character classes from the latest Unicode that Python supports in `char_classes.dat`).

**Comment by danieldk** [comment]
Thanks a lot of fixing this! Any chance a new release could be cut? NixOS is currently in beta freeze for the 20.03 releaseand a minor bump of ftfy with this change would make spaCy work with Python 3.8 on NixOS

**Comment by rspeer** [comment]
Right, thanks for the reminder.

**Comment by rspeer** [comment]
Alright, version 5.7 is uploaded.

**Comment by FernandezMathieu** [comment]
Hey guys, i'm currently working to add your package in conda-forge. Just to let you know this problem happen in Python v3.9.1.
