### ISSUE TITLE
Mojibake problem: Ë¡

### ISSUE THREAD

**Issue by MicroJackson** [LuminosoInsight/python-ftfy#140]
Hi,
```
U+00CB  Ë       [Lu] LATIN CAPITAL LETTER E WITH DIAERESIS
U+00A1  ¡       [Po] INVERTED EXCLAMATION MARK
SHOULD BE:
U+2160  Ⅰ       [Nl] ROMAN NUMERAL ONE
```

Example:
> locomotief Ae 3/6 Ë¡Ë¡ van de

Is it possible to fix this?

**Comment by rspeer** [comment]
Is there a chance the string was supposed to say `locomotief Ae 3/6 ˡˡ van de`, with two superscript ones instead of `ⅠⅠ`?

The heuristics don't currently believe that `ˡ` is a character someone would really want to use. Maybe the writer picked something that looked right out of a character map, or perhaps this is the result of OCR?

**Comment by MicroJackson** [comment]
> Is there a chance the string was supposed to say `locomotief Ae 3/6 ˡˡ van de`, with two superscript ones instead of `ⅠⅠ`?

Hmm, that is possible. The text where this sentence is from is "automatically translated", which might mean OCR like you suggested. It might be that the computer-translator assumed the Roman Ones as superscript ones. Most people write this product with regular capital i twice, some with the Roman Ones, so I assumed this was the Roman One. But you might be right that is should un-mojibake to superscript 1, and that they used OCR, which would be a first that I encountered...

**Comment by rspeer** [comment]
I can see Google Translate doing something like that.

Anyway, I am going to guess that there is no general lesson we can learn from this specific sequence of text-processing accidents, so I'll close this one.
