### ISSUE TITLE
Mojibake problem: ‹

### ISSUE THREAD

**Issue by MicroJackson** [LuminosoInsight/python-ftfy#148]
Hi,
```
U+2039  ‹       [Pi] SINGLE LEFT-POINTING ANGLE QUOTATION MARK
SHOULD BE:
U+00EF  ï       [Ll] LATIN SMALL LETTER I WITH DIAERESIS
```

Example:
> Met ge‹ntegreerde trekhaak

Is it possible to fix this?
I have many mojibake problems with the letter ï. All in the same vein as this one. Like ge¯ntegreerde or Ge´ntegreerd. Will only make a ticket for them if single character mojibake is actually fixable.

**Comment by rspeer** [comment]
Single-character mojibake is not generally fixable, because there isn't any particular evidence that the character wasn't intended (unless it's a completely useless control character like the ones that show up in Latin-1).

I appreciate seeing the evidence of which encodings get confused with one another. This one is Windows-1252 with IBM codepage 437, indicating a file that was meant to be viewed in DOS.
