### ISSUE TITLE
Mixup of latin1 and cp1251 not detected

### ISSUE THREAD

**Issue by Khris777** [LuminosoInsight/python-ftfy#156]
Hi,

I'm not sure if this is a bug or if it's me using ftfy wrong or understanding its limits.

I have cyrillic text that was encoded wrongly, it's a mixup of latin1 and cp1251, and from the docs it sounds like you support these kinds of mixups. Knowing the problem it can easily get fixed like this:

```
import ftfy
t = "Ôèëüòðóþùèé ýëåìåíò"
print(t.encode("latin_1").decode("cp1251"))
```

But my data is mixed, some strings are broken like this, others are not, so I need at least to find those that are broken, however it seems like ftfy can not discriminate between both cases.

`ftfy.fix_text(t)` returns the input string.

`ftfy.badness.sequence_weirdness(t)` returns the value 0.

Using version 5.5.1

**Comment by rspeer** [comment]
This is #18, and we don't really have a good plan for how to solve it.

**Comment by Khris777** [comment]
To solve this for myself I've been experimenting with using the name method in the unicodedata module.

I use it on each character in my string and if all characters are LATIN instead of CYRILLIC then I know it's a wrongly encoded character.

**Comment by rspeer** [comment]
I think that gets to the heart of why this problem would be easier to solve in your particular case, than it would be to solve in general in ftfy: you know that your text is supposed to be in Cyrillic characters.

The string `ýëåìåíò` could be Latin-1/Windows-1251 mojibake for "элемент". Or it could be Latin-1/Windows-1253 mojibake for "ύλεμενς". They're both plausible strings. The differences are:

- In your use case, you're expecting Russian, not Greek
- "элемент" is a word in Russian, but "ύλεμενς" is not a word in Greek

ftfy doesn't know what language you expect, and it ought to keep working the same even when there's text in a language you don't expect. And it's not trying to be a language model or a spelling checker, so it doesn't know what "is a word". That's why this is so difficult to solve.

**Comment by Khris777** [comment]
Yes, I totally understand that.

However a string like ýëåìåíò is totally unusual having 6(7) concurrent vowels and every single one of them having diacritics, so why not add rules to the `sequence_weirdness` method to detect something like that?
