### ISSUE TITLE
Problem fixing "ì¤€ë‹¤ê³" (Korean)

### ISSUE THREAD

**Issue by SuperIRabbit** [LuminosoInsight/python-ftfy#159]
Some Korean words are not fixed, e.g.,
"ì¤€ë‹¤ê³"
"ê°€ì§€ê³"

(For comparison, the following are fixed:
word = "ì¤€"
fix_encoding(word)
Output: '준'
word = "ê°€"
fix_encoding(word)
Output: '가'
)

**Comment by rspeer** [comment]
In each case, there appears to be a character missing from the mojibake (the corrupted text). If characters have been removed from the corrupted text, ftfy can't fix it, because then there isn't enough information to tell what text should have been there.

In the first case, I'm guessing that the intended word was "준다고". The UTF-8 / Windows-1252 mojibake of that string is `ì¤€ë‹¤ê³ `. There's a space on the end that is missing from your example. (It's a non-breaking space, U+A0, but ftfy understands that non-breaking spaces are sometimes replaced by the standard space, U+20.)

ftfy can decode this text when all the characters are there, including the space:

```
>>> ftfy.fix_encoding("ì¤€ë‹¤ê³ ")
'준다고'
```

If possible, I recommend that you run ftfy on the complete string that was produced by a bad encoding process, without stripping spaces or separating it into words. If a process outside of your control has stripped the spaces, some strings are going to be unrecoverable.

**Comment by rspeer** [comment]
As a guideline, you can tell when there might be characters missing because there should be a multiple of 3 of them. In a mix-up between UTF-8 and Windows-1252, each Korean character turns into 3 characters.
