### ISSUE TITLE
Cannot resolve mojibake on emoji

### ISSUE THREAD

**Issue by D-stefaang** [LuminosoInsight/python-ftfy#169]
We're getting JSON from a third party
```
{
  "title": "\\u011f\\u0178\\ufffd\\u0161 Cooked Rice"
}
```
This is supposed to correspond to the Cooked Rice emoji: 🍚
https://www.compart.com/en/unicode/U+1F35A

They also send us 
```
{
  "first_name": "Ya\\u00c3\\u00abl"
}
```
Which could be cleaned by simply going over latin1.
```
print('Ya\u00c3\u00abl')
'YaÃ«l'
print('Ya\u00c3\u00abl'.encode('latin1').decode('utf-8'))
'Yaël'
```

Any help here would be amazing.

**Comment by rspeer** [comment]
Unfortunately, ftfy isn't going to be able to automatically fix either of these.

The second example is too short to be reliably detected. If you know that latin1 / utf-8 mixups are likely, you should probably just try that encoding and decoding yourself.

The first one makes a fascinating example, because it's a Windows-1254 / utf-8 mixup, and I hadn't seen one of those in the wild before. There are two problems now:

- ftfy has never tried to recognize Windows-1254 mojibake
- the third character was an unassigned byte in Windows-1254 that has been replaced by '�', so if we did look for Windows-1254 mojibake patterns, the intended text could still have been any of these characters:

```
U+1F05A  🁚       [So] DOMINO TILE HORIZONTAL-05-06
U+1F35A  🍚      [So] COOKED RICE
U+1F39A  🎚       [So] LEVEL SLIDER
U+1F3DA  🏚       [So] DERELICT HOUSE BUILDING
U+1F41A  🐚      [So] SPIRAL SHELL
U+1F75A  🝚       [So] ALCHEMICAL SYMBOL FOR POWDERED BRICK
U+1F79A  🞚       [So] WHITE DIAMOND CONTAINING BLACK VERY SMALL DIAMOND
```

**Comment by rspeer** [comment]
OH NO. I understand how this happened.

These strings have had chardet run on them. Chardet takes the absolutely wild guess that the cooked rice emoji is Turkish text in Windows-1254... because chardet is from the '90s and has _no idea what an emoji is_.

I know ftfy is supposed to help in situations like this, but is it possible that you could just figure out whoever upstream from you is running chardet, and ask them to stop? It can't be in my scope to clean up the mess that chardet makes.

**Comment by D-stefaang** [comment]
Sure I've reached out to the 3rd party.
Thanks a lot for your investigation, it's really impressive!

**Comment by D-stefaang** [comment]
For the record.. the issue was on my end.
```
import requests
import json

resp = requests.get(url)
text = resp.text
data = json.loads(resp.text)
```
This uses `chardet` library for the text conversion.
The fix is to use the `json` method right away, see also the `response.json` docstring.
```
resp = requests.get(url)
data = resp.json()
```

**Comment by rspeer** [comment]
Thanks for the details. That's terrifying -- I had no idea that the default behavior of `requests` on a text file is to blindly accept whatever chardet says.

Even though requests provides a better path to decoding JSON, I'd still say that the issue is really on requests' end, for silently introducing encoding bugs like that.
