### ISSUE TITLE
Was a `comment` with `Ã©` by intent?

### ISSUE THREAD

**Issue by jpluimers** [LuminosoInsight/python-ftfy#179]
The last change in https://github.com/LuminosoInsight/python-ftfy/commit/7bc9a701051efdc722a39f5abc2c07746673b180#diff-d6cc00097eda5f2edb8e812a59a6c9a323d87e4f6c1e12888b534252fabf8512R506 introduced

```
"comment": "I recall the correct version of this text from a sign in the movie Amélie. Unfortunately, we can't help her twin AmÃ©lie, who makes mojibaked signs.",
```

I wonder if the `Ã©` was by intent, or that it should become `è` to give `Amélie` a twin named `Amèlie`.

It is till present in the current https://github.com/LuminosoInsight/python-ftfy/blob/master/tests/test_cases.json#L926

**Comment by Tahnan** [comment]
It was by intent.  The joke was that "Amélie" makes signs, and "AmÃ©lie" makes mojibaked signs (which is why her name contains mojibake).  So if AmÃ©lie made a sign that read "OÃ™ ET QUAND", ftfy couldn't correct it (when the original marked-as-fail test was introduced) but can now.

Potentially a little obscure as a joke, but intentional nonetheless.
