### ISSUE TITLE
Fail in fix

### ISSUE THREAD

**Issue by RahulKulhari** [LuminosoInsight/python-ftfy#52]
Text: 

`text = "a€¢    Strong telecom background in BSS area a€“ Preferably Order Management"`
`ftfy.fix_text(text)`

When i am passing text to fix text it is returning 

> UnicodeError: Hey wait, this isn't Unicode.

Then i am converting text to unicode and passing to `fix_text` function

`utext  = unicode(text, encoding, errors=errors)`

Output:
>u'a\u20ac\xa2    Strong telecom background in BSS area a\u20ac\u201c Preferably Order Management'

```
In [10]: ftfy.fix_text(utext)
Out[10]: u'a\u20ac\xa2    Strong telecom background in BSS area a\u20ac" Preferably Order Management'
```
I deal with this kind of data alot.
How to solve this issue ?

**Comment by RahulKulhari** [comment]
@rspeer do u have any suggestion ?

**Comment by rspeer** [comment]
Someone has already replaced the character `â` by `a` in your data, possibly because of a paranoid approach to Unicode that involves removing all accents. Unfortunately, this means the information needed to reconstruct your text has been lost. Your text pipeline has more problems than ftfy can fix.

You should go back to where you got the text from, if you have any control over that, and see if you can fix its accent-removing issue (along with its encoding mistake, which is that it's reading UTF-8 text as if it's Windows-1252 text).

By the way, in Python 2, you should make a Unicode string literal by putting `u` before the quotation marks, as in `u"a€¢"`. The UnicodeError you got should contain a link to the [Python Unicode HOWTO](https://docs.python.org/2/howto/unicode.html), which may help.
