### ISSUE TITLE
Mojibake problem: â"¢

### ISSUE THREAD

**Issue by MicroJackson** [LuminosoInsight/python-ftfy#99]
Hi,
Thanks for the last update, it fixed my problem. 👍 
However, I got more problems with mojibake. 
The word is: `PowerHouseâ"¢`. It should be `PowerHouse™`.
The letters are: 
`U+00E2  â       [Ll] LATIN SMALL LETTER A WITH CIRCUMFLEX`
`U+0022  "       [Po] QUOTATION MARK`
`U+00A2  ¢       [Sc] CENT SIGN`

Is it possible to fix this?
Also, is this style of reporting acceptable? Because I have a few more mojibake problems.

**Comment by rspeer** [comment]
This style of reporting is fine! If the problems turn out to be related I can merge the reports.

I think this would be hard to fix with any confidence. I can tell that the straight quote `"` was once a Windows-1252 curly quote, but as a result there are multiple characters that would mojibake the same way.

This shows the three different possibilities:
```
>>> windows_quotes = '“”„'
>>> for q in windows_quotes:
...     text = 'PowerHouseâ{}¢'.format(q)
...     print("{} -> {}".format(text, ftfy.fix_text(text)))
... 
PowerHouseâ“¢ -> PowerHouseⓢ
PowerHouseâ”¢ -> PowerHouse┢
PowerHouseâ„¢ -> PowerHouse™
```

There isn't a way to tell which one is right, except that `™` is a more common character.

I'm curious, because replacing `„` with `"` doesn't seem like a particularly common Unicode operation, but it's part of `ftfy.fixes.uncurl_quotes`. Did you run `uncurl_quotes` on this text before running the rest of ftfy on it? If so, it's a good example of why it's best to run all the fixes, the way that `ftfy.fix_text` does.

**Comment by MicroJackson** [comment]
Ah I understand, that's too bad.

I think the Windows-1252 curly quote you talk about is correct, but that information is lost when it comes to me. This "PowerHouse" text goes through ~4 different systems with their own encoding before I get my hands on it. So to answer your question, no, I do not use the ftfy.fixes.uncurl_quotes, it gets lost along the way, which is out of my control. 
The last part of the system is probably Windows-1252 -> UTF-8, where the problem starts to show (it was still fine in Windows-1252), where the encoding or decoding is wrong. The UTF-8 then goes to Unicode in Python 3.

Anyhow, it seems to be best to make a manual rule for it then in my code to replace â"¢ to ™.
